# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPIxWpw0-QsYbgQ2jSl4x8LXMeSKOn8y
"""

import streamlit as st

# Configuration de la page
st.set_page_config(page_title="ELECTRO SOLUT – Vente d'ordinateurs", layout="wide")

# --- Bannière avec logo ---
st.markdown("""
    <div style="background-color:#0A5275;padding:20px;border-radius:10px;">
        <h1 style="color:white;text-align:center;">💻 ELECTRO SOLUT</h1>
        <h3 style="color:white;text-align:center;">Votre partenaire en solutions informatiques</h3>
    </div>
""", unsafe_allow_html=True)

# --- Présentation de l'entreprise ---
st.header("📢 À propos de nous")
st.write("""
**ELECTRO SOLUT** est une entreprise spécialisée dans la vente d'ordinateurs portables, de bureau et d’accessoires tech haut de gamme.
Nous proposons des produits fiables, performants et adaptés à tous les besoins (étudiants, professionnels, gamers, etc.).
""")

import streamlit as st

# --- Style pour uniformiser les images ---
st.markdown("""
    <style>
    img {
        height: 200px !important;
        object-fit: cover;
        width: 100% !important;
        border-radius: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# --- Catalogue de produits ---
st.header("🛒 Nos produits")

st.markdown("""
    <style>
    .product-card {
        border: 1px solid #e0e0e0;
        border-radius: 12px;
        padding: 15px;
        margin-bottom: 20px;
        text-align: center;
        background: white;
        position: relative;
        box-shadow: 0 4px 8px rgba(0,0,0,0.08);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        height: 100%;
    }
    .product-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 6px 12px rgba(0,0,0,0.12);
    }
    .badge-new {
        position: absolute;
        top: 12px;
        left: 12px;
        background: #00acc1;
        color: white;
        padding: 4px 10px;
        font-size: 12px;
        border-radius: 4px;
        font-weight: 600;
    }
    .badge-discount {
        position: absolute;
        top: 12px;
        right: 12px;
        background: #ff6b6b;
        color: white;
        padding: 4px 10px;
        font-size: 12px;
        border-radius: 4px;
        font-weight: 600;
    }
    .product-image {
        width: 80%;
        height: 150px;
        object-fit: contain;
        margin: 10px auto;
        transition: transform 0.3s ease;
    }
    .product-image:hover {
        transform: scale(1.05);
    }
    .product-title {
        font-size: 16px;
        font-weight: 600;
        margin: 15px 0 10px;
        color: #333;
    }
    .price-container {
        margin: 10px 0;
    }
    .price {
        font-size: 18px;
        font-weight: 700;
        color: #2e7d32;
    }
    .product-specs {
        font-size: 14px;
        color: #555;
        margin: 10px 0;
        line-height: 1.4;
        min-height: 60px;
    }
    .add-to-cart {
        background: #4CAF50;
        color: white;
        border: none;
        padding: 8px 20px;
        border-radius: 4px;
        font-weight: 600;
        margin-top: 10px;
        cursor: pointer;
        transition: background 0.3s;
        width: 100%;
    }
    .add-to-cart:hover {
        background: #3d8b40;
    }
    </style>
""", unsafe_allow_html=True)

cols = st.columns(3)

with cols[0]:
    st.markdown("""
    <div class="product-card">
        <div class="badge-new">NOUVEAU</div>
        <img src="https://images.unsplash.com/photo-1517336714731-489689fd1ca8" class="product-image" alt="ProBook"/>
        <p class="product-title">Ordinateur portable ProBook</p>
        <div class="price-container">
            <span class="price">899 €</span>
        </div>
        <p class="product-specs">💻 i7-1165G7 | 16GB RAM | 512GB SSD | Windows 11 Pro</p>
        <p class="product-specs">💡 Idéal pour les professionnels</p>
        <button class="add-to-cart">Ajouter au panier</button>
    </div>
    """, unsafe_allow_html=True)

with cols[1]:
    st.markdown("""
    <div class="product-card">
        <div class="badge-discount">PROMO</div>
        <img src="https://i5.walmartimages.ca/images/Enlarge/729/870/6000199729870.jpg" class="product-image" alt="X-Treme"/>
        <p class="product-title">Ordinateur Gamer X-Treme</p>
        <div class="price-container">
            <span class="price">1299 €</span>
        </div>
        <p class="product-specs">🎮 RTX 3060 | i7-12700H | 32GB RAM | 1TB SSD</p>
        <p class="product-specs">🔥 Hautes performances gaming et montage vidéo</p>
        <button class="add-to-cart">Ajouter au panier</button>
    </div>
    """, unsafe_allow_html=True)

with cols[2]:
    st.markdown("""
    <div class="product-card">
        <div class="badge-new">NOUVEAU</div>
        <img src="https://www.electronicscritique.com/wp-content/uploads/2020/11/ACEPC-Mini-PC-Windows-10-Pro-Celeron-J3455-1024x827.jpg" class="product-image" alt="Mini PC"/>
        <p class="product-title">Mini PC Compact</p>
        <div class="price-container">
            <span class="price">499 €</span>
        </div>
        <p class="product-specs">🖥️ Celeron J3455 | 8GB RAM | 128GB SSD | Windows 10 Pro</p>
        <p class="product-specs">🧳 Ultra-portable, idéal pour les déplacements</p>
        <button class="add-to-cart">Ajouter au panier</button>
    </div>
    """, unsafe_allow_html=True)

# --- Formulaire de contact ---

st.header("Contactez-nous")

with st.form(key='contact_form'):
    name = st.text_input("Nom")
    email = st.text_input("Email")
    message = st.text_area("Message")
    submit_button = st.form_submit_button(label='Terminer')
    if submit_button:
        st.markdown(f"""
            <form action="https://formsubmit.co/brousybah08@gmail.com" method="POST">
                <input type="hidden" name="_captcha" value="false">
                <input type="hidden" name="_next" value="https://ton-site.com/merci">
                <input type="text" name="Nom" value="{name}" hidden>
                <input type="email" name="Email" value="{email}" hidden>
                <textarea name="Message" hidden>{message}</textarea>
                <button type="submit">Envoyer</button>
            </form>
        """, unsafe_allow_html=True)
        st.write("✅ Merci pour votre message ! Nous vous répondrons dans les plus brefs délais.")

st.markdown("""
### 📞 Vous pouvez aussi nous appeler :
[**Appeler maintenant**](tel:+3374502452)
""", unsafe_allow_html=True)

# --- Pied de page ---
st.markdown("""
    <hr>
    <div style="text-align:center;">
        <p>© 2025 ELECTRO SOLUT – Tous droits réservés.</p>
        <p>📧 brousybah08@gmail.com | 📞 +33 7 45 50 24 52</p>
    </div>
""", unsafe_allow_html=True)
