# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPIxWpw0-QsYbgQ2jSl4x8LXMeSKOn8y
"""

import streamlit as st

# Configuration de la page
st.set_page_config(page_title="ELECTRO SOLUT – Vente d'ordinateurs", layout="wide")

# --- Bannière avec logo ---
st.markdown("""
    <div style="background-color:#0A5275;padding:20px;border-radius:10px;">
        <h1 style="color:white;text-align:center;">💻 ELECTRO SOLUT</h1>
        <h3 style="color:white;text-align:center;">Votre partenaire en solutions informatiques</h3>
    </div>
""", unsafe_allow_html=True)

# --- Présentation de l'entreprise ---
st.header("📢 À propos de nous")
st.write("""
**ELECTRO SOLUT** est une entreprise spécialisée dans la vente d'ordinateurs portables, de bureau et d’accessoires tech haut de gamme.
Nous proposons des produits fiables, performants et adaptés à tous les besoins (étudiants, professionnels, gamers, etc.).
""")


# --- Style pour uniformiser les images ---
st.markdown("""
    <style>
    img {
        height: 200px !important;
        object-fit: cover;
        width: 100% !important;
        border-radius: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# --- Catalogue de produits ---

# ---- Initialisation ----
def init_panier():
    if 'panier' not in st.session_state:
        st.session_state.panier = []

# ---- CSS ----
def load_css():
    st.markdown("""
    <style>
    .product-card {
        border: 1px solid #e0e0e0;
        border-radius: 12px;
        padding: 15px;
        margin-bottom: 20px;
        text-align: center;
        background: white;
        position: relative;
        box-shadow: 0 4px 8px rgba(0,0,0,0.08);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        height: 100%;
    }
    /* ... (garder le reste du CSS) ... */
    </style>
    """, unsafe_allow_html=True)

# ---- Gestion du panier ----
def ajouter_au_panier(produit, prix):
    for item in st.session_state.panier:
        if item['nom'] == produit:
            item['quantite'] += 1
            st.success(f"Quantité mise à jour pour {produit}!")
            return
    
    st.session_state.panier.append({
        'nom': produit,
        'prix': prix,
        'quantite': 1
    })
    st.success(f"{produit} ajouté au panier!")

def afficher_panier():
    st.sidebar.header("🛒 Votre Panier")
    
    if not st.session_state.panier:
        st.sidebar.write("Votre panier est vide")
        return
    
    total = 0
    for i, item in enumerate(st.session_state.panier):
        col1, col2, col3 = st.sidebar.columns([5, 3, 1])
        with col1:
            st.write(f"**{item['nom']}**")
        with col2:
            st.write(f"{item['quantite']} × {item['prix']}€")
        with col3:
            if st.button("❌", key=f"del{i}"):
                gerer_suppression(i)
        
        total += item['prix'] * item['quantite']
    
    st.sidebar.markdown("---")
    st.sidebar.markdown(f"**Total : {total} €**")
    
    if st.sidebar.button("Vider le panier", use_container_width=True):
        st.session_state.panier = []
        st.rerun()
    
    if st.sidebar.button("Passer commande", type="primary", use_container_width=True):
        passer_commande()

def gerer_suppression(index):
    if st.session_state.panier[index]['quantite'] > 1:
        st.session_state.panier[index]['quantite'] -= 1
    else:
        st.session_state.panier.pop(index)
    st.rerun()

def passer_commande():
    st.sidebar.success("Commande passée avec succès!")
    st.session_state.panier = []
    st.rerun()

# ---- Affichage produits ----
def creer_carte_produit(produit, prix, specs, image, badge=None):
    with st.container():
        st.markdown(f"""
        <div class="product-card">
            {f'<div class="badge-{badge}">{badge.upper()}</div>' if badge else ''}
            <img src="{image}" class="product-image" alt="{produit}"/>
            <p class="product-title">{produit}</p>
            <div class="price-container">
                <span class="price">{prix} €</span>
            </div>
            <p class="product-specs">{specs}</p>
        </div>
        """, unsafe_allow_html=True)
        
        if st.button("Ajouter au panier", key=produit, use_container_width=True):
            ajouter_au_panier(produit, prix)

def afficher_catalogue():
    st.header("🛒 Nos produits informatique ")
    cols = st.columns(3)
    
    with cols[0]:
        creer_carte_produit(
            produit="ProBook",
            prix=899,
            specs="💻 i7-1165G7 | 16GB RAM | 512GB SSD | Windows 11 Pro",
            image="https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
            badge="new"
        )
    
    with cols[1]:
        creer_carte_produit(
            produit="X-Treme",
            prix=1299,
            specs="🎮 RTX 3060 | i7-12700H | 32GB RAM | 1TB SSD",
            image="https://i5.walmartimages.ca/images/Enlarge/729/870/6000199729870.jpg",
            badge="discount"
        )
    
    with cols[2]:
        creer_carte_produit(
            produit="Mini PC",
            prix=499,
            specs="🖥️ Celeron J3455 | 8GB RAM | 128GB SSD | Windows 10 Pro",
            image="https://www.electronicscritique.com/wp-content/uploads/2020/11/ACEPC-Mini-PC-Windows-10-Pro-Celeron-J3455-1024x827.jpg",
            badge="new"
        )

# ---- Application principale ----
def main():
    init_panier()
    load_css()
    afficher_catalogue()
    afficher_panier()

if __name__ == "__main__":
    main()

# --- Formulaire de contact ---

st.header("Contactez-nous")

with st.form(key='contact_form'):
    name = st.text_input("Nom")
    email = st.text_input("Email")
    message = st.text_area("Message")
    submit_button = st.form_submit_button(label='Terminer')
    if submit_button:
        st.markdown(f"""
            <form action="https://formsubmit.co/brousybah08@gmail.com" method="POST">
                <input type="hidden" name="_captcha" value="false">
                <input type="hidden" name="_next" value="https://ton-site.com/merci">
                <input type="text" name="Nom" value="{name}" hidden>
                <input type="email" name="Email" value="{email}" hidden>
                <textarea name="Message" hidden>{message}</textarea>
                <button type="submit">Envoyer</button>
            </form>
        """, unsafe_allow_html=True)
        st.write("✅ Merci pour votre message ! Nous vous répondrons dans les plus brefs délais.")

st.markdown("""
### 📞 Vous pouvez aussi nous appeler :
[**Appeler maintenant**](tel:+3374502452)
""", unsafe_allow_html=True)

# --- Pied de page ---
st.markdown("""
    <hr>
    <div style="text-align:center;">
        <p>© 2025 ELECTRO SOLUT – Tous droits réservés.</p>
        <p>📧 brousybah08@gmail.com | 📞 +33 7 45 50 24 52</p>
    </div>
""", unsafe_allow_html=True)
